feedback/urls.py
from django.conf.urls import url

from . import views

app_name = "feedback"
urlpatterns = [
    # ex: /submit_feedback/
    url(r"^submit_feedback/$", views.submit_feedback, 
       name="submit_feedback"),
    # ex: /view_feedback_list/
    url(r"^view_feedback_list/$", views.view_feedback_list, 
        name="view_feedback_list"),       
   # ex: /view_feedback/1/
    url(r"^view_feedback/(?P<feedback_id>[0-9]+)/$",
       views.view_feedback, name = "view_feedback"),
]    

feedback/models.py
from django.db import models


class SubmitFeedback(models.Model):
    your_name = models.CharField(max_length=100,)
    your_feedback = models.TextField()
    your_email = models.EmailField(blank=True)
    your_file = models.FileField(blank=True)
    date = models.DateTimeField()
    your_subject = models.CharField(max_length=25,)
       
    has_been_read = models.BooleanField(default=False)

feedback/forms.py
from django.forms import ModelForm, TextInput, Textarea, EmailInput, FileInput


from .models import SubmitFeedback

class SubmitFeedbackForm(ModelForm):
    class Meta:
        model = SubmitFeedback
        fields = ["your_subject", "your_feedback", "your_name",
                 "your_email", "your_file",         
        ]
        
        labels = {
            "your_subject" : ("Subject"),
            "your_feedback": ("Feedback"),
            "your_name"    : ("Name"),
            "your_email"   : ("Email"),
            "your_file"    : ("File"),
        }
         
        widgets = {
            'your_subject': TextInput(attrs={
                'placeholder': 'Subject',
                'class': 'form-control',
            }),
            
            'your_feedback': Textarea(attrs={
                'placeholder': 'Feedback',
                'class': 'form-control',
            }),
            
            'your_name': TextInput(attrs={
                'placeholder': 'Name',
                'class': 'form-control',
            }),
            
            'your_email': EmailInput(attrs={
                'placeholder': 'Email',
                'class': 'form-control',
            }),   
        }
        

feedback/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.mail import send_mail
from django.utils import timezone
from django.contrib import messages

from .forms import SubmitFeedbackForm
from .models import SubmitFeedback

def submit_feedback(request):
    # POST request -- save the submitted feedback if it's valid
    if request.method == "POST":
        form = SubmitFeedbackForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['your_email']:
                send_email(form.cleaned_data)
            messages.success(request, "Thank you for your feedback, %s."
                                %(form.cleaned_data["your_name"].split()[0]))                                    
            form = form.save(commit=False)
            form.date = timezone.now() 
            form.save()
            return HttpResponseRedirect(reverse('feedback:submit_feedback'))
                           
   # Any other kind of request -- create the empty feedback form        
    else:
        form = SubmitFeedbackForm()
   
    # Serve the empty feedback form to the user     
    return render(request, "feedback/submit_feedback.html", {"form": form})

def view_feedback_list(request):
    feedback = SubmitFeedback.objects.order_by('-date')
    
    return render(request, 'feedback/view_feedback_list.html', {'feedback': feedback})

def view_feedback(request, feedback_id):
    feedback = get_object_or_404(SubmitFeedback, pk=feedback_id)
    feedback.has_been_read = True
    feedback.save()
    
    return render(request, 'feedback/view_feedback.html', {'feedback': feedback})
    
        

def send_email(form_data):
    subject = 'Thank you for your feedback'
    message = '''Hi %s, 
Thank you for your feedback. We may
contact you for more information with regard to your feedback. 
For your convenience, we have reproduced your feedback below: 

%s'''%(form_data['your_name'], form_data['your_feedback'])
    sender = 'joshgoddard@gmail.com'
    receiver = (form_data['your_email'],)            
    send_mail(subject, message, sender, receiver)
        

feedback/templates/feedback/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="/static/feedback/css/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
{% block body_content %}
{% endblock %}
</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="/static/feedback/css/bootstrap/js/bootstrap.min.js"></script>
</body>

feedback/templates/feedback/submit_feedback.html
{% extends 'feedback/base.html' %}

{% block title %}Submit Feedback{% endblock %}

{% block body_content %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" role="alert">
        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
    </div>
    {% endfor %}
{% endif %}
<h2 class= "text-center">  Submit Feedback </h2>
<form action="{% url 'feedback:submit_feedback'%}" method="post">
    {% csrf_token %}
    {% for field in form %}
    <div class="fieldWrapper form-group">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}
<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock %}

feedback/templates/feedback/view_feedback.html
{% extends 'feedback/base.html' %}

{% block title %}View Feedback{% endblock %}

{% block body_content %}
<table class="table">
    <thead>
      <tr>
        <th>Subject</th>
        <th>Name</th>
        <th>Email</th>
        <th>Date</th>
      </tr>
    </thead>
        <tr>
            <td>{{feedback.your_subjec}}t</td>
            <td>{{feedback.your_name}}</td>
            <td>{{feedback.your_email}}</td>
            <td>{{feedback.date}}</td>    
        <tr>
</table>
<blockquote>
  <p>{{ feedback.your_feedback }}</p>
</blockquote>
{% endblock %}

feedback/templates/feedback/view_feedback_list.html
{% extends 'feedback/base.html' %}

{% block title %}View Feedback List{% endblock %}

{% block body_content %}
{% if feedback %}
<h2 class= "text-center">Feedback List </h2>
<table class="table">
    <thead>
      <tr>
        <th>Subject</th>
        <th>Name</th>
        <th>Date</th>
         <th></th>
      </tr>
    </thead>
    {% for entry in feedback %}
        <tr class={% if entry.has_been_read %}"" { % else % } "" {% endif %} "info" >
            <td> 
                <a href="{% url 'feedback:view_feedback' entry.id %}">{{ entry.your_subject }}</a></td>
            <td> {{ entry.your_name}} </td>
            <td> {{ entry.date}} </td>  
            <td>   <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Action
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <li><a href="{% url 'feedback:view_feedback' entry.id %}">View</a></li>
    <li><a href="#">Move to trash</a></li>
    <li><a href="#">Mark as read</a></li>
  </ul>
</div>              </td>
        </tr>
    {% endfor %}
</table>
{% else %}
<p>No feedback.</p>
{% endif %}

{% endblock %}